### ISSUE TITLE
QWeb library import fails on Ubuntu (20.04.5 LTS) due to Pynput

### ISSUE THREAD

**Issue by jcsingh** [qentinelqi/qweb#103]
**Describe the bug**
Python (3.8.12) import of QWeb (2.0.4) fails on Ubuntu (20.04.5 LTS)

**To Reproduce**
1. On Ubuntu (20.04.5 LTS) open terminal and start python console 
2. Import QWeb
3. See below error

[ WARN ] Cannot import pynput.keyboard, no display detected
--
  | [ ERROR ] Error in file '/workdir/resources/UI_Common.resource' on line 2: Importing library 'QWeb' failed: ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))
  |  
  | Try one of the following resolutions:
  |  
  | * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.8/site-packages/QWeb/__init__.py", line 26, in <module>
  | from QWeb.keywords import (alert, browser, window, frame, element, text, checkbox, input_,
  | File "/usr/local/lib/python3.8/site-packages/QWeb/keywords/text.py", line 27, in <module>
  | from pynput.keyboard import Controller
  | File "/usr/local/lib/python3.8/site-packages/pynput/__init__.py", line 40, in <module>
  | from . import keyboard
  | File "/usr/local/lib/python3.8/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
  | backend = backend(__name__)
  | File "/usr/local/lib/python3.8/site-packages/pynput/_util/__init__.py", line 76, in backend
  | raise ImportError('this platform is not supported: {}'.format(
  | PYTHONPATH:
  | /workdir
  | /usr/local/lib/python38.zip
  | /usr/local/lib/python3.8
  | /usr/local/lib/python3.8/lib-dynload
  | /usr/local/lib/python3.8/site-packages

**Expected behavior**
Python should be able to import QWeb module

**Screenshots**
<img width="1290" alt="Screen Shot 2022-10-14 at 8 04 10 PM" src="https://user-images.githubusercontent.com/20757212/195959520-dbf07c20-8fef-4ba6-85d8-915e675157f8.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome (headless) 106.0.5249.61/chromedriver_linux64/chromedriver
 - Version - 20.04.5 LTS

**Smartphone (please complete the following information):**
 - Python: 3.8.12

**Additional context**
The exception is caused by Pynput module on Ubuntu

**Comment by tkoukkari** [comment]
hi, thanks for the bug report. We do have linux in our acceptance tests. They used to be run on Ubuntu 20.04 but currently it's using 22.04 already. In any case we have not seen this. Can you tell a bit more about your environment / configuration? The "no display detected" message is interesting and probably meaningful.

**Comment by tkoukkari** [comment]
X server needs to be running and it seems like it's not. If you look at our headless acceptance tests, you will find we do something like this for example:

```
DISPLAY: :88
...
sudo apt-get install matchbox scrot
Xvfb $DISPLAY -screen 0 1920x1080x24 & sleep 1
matchbox-window-manager -use_titlebar no &

```

**Comment by jcsingh** [comment]
Thanks @tkoukkari. Steps in your last comment fixed the issue for me.

**Comment by tkoukkari** [comment]
> Thanks @tkoukkari. Steps in your last comment fixed the issue for me.
> 
> 
> 

Great! 

Tuomas
