### ISSUE TITLE
Add keyword for getting current browser URL location

### ISSUE THREAD

**Issue by kalyncoose** [qentinelqi/qweb#11]
**Is your feature request related to a problem? Please describe.**
I need to parse the browser URL for parameters, however there is no keyword in QWeb to obtain the current browser URL.

**Describe the solution you'd like**
A similar keyword to SeleniumLibrary, called [Get Location](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Get%20Location), which returns the browser URL as text.

**Describe alternatives you've considered**
A temporary work-around is to use the [Execute Javascript](https://qentinelqi.github.io/qweb/QWeb.html#Execute%20Javascript) keyword using the `window` like so:
```
Execute Javascript  return window.location.href;  $url
```

**Additional context**
n/a

**Comment by tkoukkari** [comment]
This will be included in next release. This was actually originally omitted in purpose since we did not have many use cases where we didn't know the current url, but I realize there are that kind of use cases as well. We will also add "Verify Location" or something similar.

**Comment by tkoukkari** [comment]
Version 1.0.4 released with new keywods:

- GetUrl
- VerifyUrl
- GetTitle
- VerifyTitle
- Back

You can update with:
`pip install -U QWeb`
