### ISSUE TITLE
Anchor texts that are also numbers are not working

### ISSUE THREAD

**Issue by ansevala** [qentinelqi/qweb#13]
**Describe the bug**
In cases where there are items in a list, with only some number distinguishing them - like a serial number - there isn't a way to use that as an anchor, because it will be interpreted as an index. For example, I'm never interested in 1205913904217382th item, but that might be useful as text.

**To Reproduce**
1. Open following web page:
`<div>123</div><div><a href="incorrect">LINK</a></div><br><div>456</div><div><a href="correct">LINK</a></div>`
2. `Click Text  LINK  456`
3. See error
`QWebInstanceDoesNotExistError: Found 2 elements. Given anchor was 456`

**Expected behavior**
I'd like to have either fallback to the other locating method - if anchor is a number, first try it as an index, then as a text anchor - or some way to implicate I'm not interested in indexes - a kwarg, like `text_anchor=true`, or quotation marks around the anchor.

**Comment by tkoukkari** [comment]
hi, will be included in next release. I'm still wondering which is better, quotation marks or specific argument.

**Comment by tkoukkari** [comment]
Added new argument in order to be specific. This will work as expected with:

ClickText &emsp;           LINK &emsp;             456 &emsp;    anchor_type=text

**Comment by ansevala** [comment]
Great job! Thanks!

**Comment by tkoukkari** [comment]
Fixed and included in v.1.0.4
