### ISSUE TITLE
Unable to configure Jenkins pipeline for Robot Framework- Qweb Framework

### ISSUE THREAD

**Issue by prakaam** [qentinelqi/qweb#131]
**Describe the bug**
The QWeb Framework that is developed using robot framework is triggering the error #Importing library 'QWeb' failed: DisplayConnectionError: Can't connect to display ":0": [Errno 111] Connection refused#

**To Reproduce**
The Jenkins file is attached.
[JenkinsFile.txt](https://github.com/qentinelqi/qweb/files/12847784/JenkinsFile.txt)

**Comment by tkoukkari** [comment]
You probably need to install xvfb and start it, Probably good idea to install matchbox or some other window manager too.

```
apt-get -y install xvfb matchbox
```

```
sh 'Xvfb $DISPLAY -screen 0 1920x1080x24 & sleep 1'
sh 'matchbox-window-manager -use_titlebar no &'
```
