### ISSUE TITLE
Integration with Browserstack doesn't seem to work

### ISSUE THREAD

**Issue by anthonyOSF** [qentinelqi/qweb#135]
I try to run my QWeb tests from VisualStudio code on Browserstack but I get an error: 
**Suspended due to logged failure: QWebException: Incorrect Browser name.**

![2023-12-04_17h11_05](https://github.com/qentinelqi/qweb/assets/83226477/ef2e5977-e79b-49a2-bafe-3ac40aba0a94)

I saw some modification in the last release, there seems to be a problem

Thanks in advance

**Comment by tkoukkari** [comment]
Try using "Chrome" as name. 

We'll fix it to be case insensitive here as well...

**Comment by anthonyOSF** [comment]
Hello @tkoukkari , thank you for your answer ! 
I have the same error with "Chrome" as name 
![2023-12-18_12h27_50](https://github.com/qentinelqi/qweb/assets/83226477/a030c7ad-1b01-436e-8706-7ea5c95be5f3)

**Comment by tkoukkari** [comment]
hmm, works fine here

**Comment by anthonyOSF** [comment]
@tkoukkari Should I add something more than what you see in my screenshot? Can you possibly share your code or does it work?

**Comment by tkoukkari** [comment]
Does the error say anything more? 

It works using the example from "OpenBrowser" documentation:

```
${PROVIDER}=    Set Variable      bs
${USERNAME}=    Set Variable      [MY USER]
${APIKEY}=      Set Variable      [MY API TOKEN]
${PROJECTNAME}=    Set Variable   qweb_run
${RUNID}=       Set Variable      qweb_run
${BSOS}=        Set Variable      windows
...
OpenBrowser     https://www.google.com    chrome
```
Results in this:
![image](https://github.com/qentinelqi/qweb/assets/37436311/ad81c06d-9e55-4cac-bc05-e8b143507899)

**Comment by anthonyOSF** [comment]
Not really, I only have this error, Maybe I shouldn't put the username and accesskey directly in the set variable?
![2023-12-18_15h08_14](https://github.com/qentinelqi/qweb/assets/83226477/745b57c3-d246-4a0a-9c08-b8c491ba032e)

**Comment by tkoukkari** [comment]
I really don't think it matters. It should also tell you if username or APIKEY are incorrect.

What's the url like? There isn't any spaces or special characters there, or are there?

**Comment by anthonyOSF** [comment]
I have try with https://www.google.com as URL and i have the same error

**Comment by tkoukkari** [comment]
Can you login to your browserstack subscription and check the run there? It should have more information

**Comment by tkoukkari** [comment]
Also check if you have this robot variable defined somewhere else (and what is the value of that):
`${BROWSER}`

**Comment by anthonyOSF** [comment]
@tkoukkari Thx to help me to find a solution 
I have absolutely nothing in Browserstack because nothing is launched
However, I am used to using it with selenium and it works but I would like to switch to QWeb precisely

I don't have ${BROWSER} anywhere, here is my simple testcase with nothing around it.
My setting.json includes my VSCode settings only
![2023-12-18_17h02_40](https://github.com/qentinelqi/qweb/assets/83226477/53c267be-e162-4f2e-98f6-0552bf39c116)

**Comment by tkoukkari** [comment]
hi,
the one in latest screenshot should not work as you don't have **http://** or **https://** in front of the www in url.

The error message should be different though.

**Comment by tkoukkari** [comment]
If possible, could you join the robot framework's Slack (see _Community_ section in this repo's readme) and join "QWeb" channel there? We could maybe have a screen sharing session today?

**Comment by anthonyOSF** [comment]
@tkoukkari I can't join the slack channel without this kind of email domain
Please send me an invitation on 
![2023-12-19_10h32_46](https://github.com/qentinelqi/qweb/assets/83226477/bf277e10-d871-4c38-a42f-a77b3f41aeaf)

**Comment by anthonyOSF** [comment]
As you said, there was indeed a ${BROWSER} which was hard-coded in my global setting.json of my VSCode
Thank you very much for your support
