### ISSUE TITLE
Table cell index notation differences

### ISSUE THREAD

**Issue by turunenm** [qentinelqi/qweb#155]
Targeting table cells can be done with two different notations which differ in how they behave.
One style disregards header elements `th` and one does not

excludes headers
`ClickCell    r2c4`

includes headers
`ClickCell    r3/c4` 

This should be either documented as it is now
Or modify the notation behaviors so that they work the same and that the header inclusion can be controlled with an argument

**Comment by tkoukkari** [comment]
Improved documentation related to this in release 3.2.2
