### ISSUE TITLE
ClickCheckbox keyword started failing in new release

### ISSUE THREAD

**Issue by DeependraNielsen** [qentinelqi/qweb#158]
**Describe the bug**
ClickCheckbox keyword started failing in new release. 
Error we are getting 
FAIL: TypeError: get_checkbox_by_locator() got an unexpected keyword argument 'kwargs'

**To Reproduce**
1. Click and checkbox using ClickCheckbox using nearby string.
2. Error occurs

** Screenshot
Below change seems to be the root cause
<img width="659" alt="image" src="https://github.com/qentinelqi/qweb/assets/174092753/e9ebd64c-34ad-4bbb-804b-1651b3f996b5">

**Expected behavior**
Checkbox should be checked/unchecked.

**Comment by tkoukkari** [comment]
hi, that was regression in version 3.3.2 and the change fixes that. Please update to version 3.3.3

**Comment by tkoukkari** [comment]
Closing this as fix has been available in version 3.3.3.
