### ISSUE TITLE
VerifyTextCount doesn't work if real count is zero and expected_count is more than zero

### ISSUE THREAD

**Issue by ansevala** [qentinelqi/qweb#19]
**Describe the bug**
VerifyTextCount always passes when text isn't found at all. It only works properly when text is found X times.

**To Reproduce**
1. Go to _https://en.wikipedia.org/wiki/New_Britain_friarbird_
2. VerifyTextCount of any text that is not on the page expecting it is there, e.g.
```VerifyTextCount    Punatulkku    1```
3. Keyword passes

**Expected behavior**
Keyword should be failing.

**Comment by tkoukkari** [comment]
Fixed, will be included in version **1.0.5** which will be released this week.
