### ISSUE TITLE
Browser comparison spacing seems to be off.

### ISSUE THREAD

**Issue by mkorpela** [qentinelqi/qweb#2]
**Describe the bug**
On the https://qentinel.com/qweb-open-source-automation-library/ page there is a visual comparison of Browser library and QWeb.

![image](https://user-images.githubusercontent.com/136885/111660212-85c6fa00-8816-11eb-8cb1-c8b728769263.png)

The spacing on the `Get Text` keywords seems to be wrong. Robot Framework uses 2 or more spaces as an argument separator.

So `Get Text              h1 == Your cart is empty` should be "Get Text &nbsp;    h1 &nbsp;   == &nbsp;  Your cart is empty"

**Comment by Snooz82** [comment]
Yes and on Qweb side

```robotframework
DropDown       Size Large
```

Is also missing a space between Size and Large.

and the Browser `Select by Option` has also bugs in the arguments.

**Comment by Snooz82** [comment]
It seems to me that there are generally a lot of spaces wrong.

and the Browser library test would actually fail in that case.

The AssertionOperator `==` verifies that a value is equal with the expected value.
You test object has a `.` at the end of the `h1`.
If want to check if a text contains something, you could use the `contains` operator.

The test could also uses css selectors, that are a bit better on that test object.
like:
```robotframework
Click    [alt="Remove item"]
```

**Comment by tkoukkari** [comment]
Hi,
This comparison is not hosted in this repo, so in general this issue does not belong here. However, we did forward the message.

Formatting is probably just a copy-paste problem or something. Yes, css selectors could have been used as well.

The comparison has now been removed.
