### ISSUE TITLE
Force refresh parameter for Refresh Page keyword

### ISSUE THREAD

**Issue by kalyncoose** [qentinelqi/qweb#48]
**Is your feature request related to a problem? Please describe.**
The [Refresh Page](https://qentinelqi.github.io/qweb/QWeb.html#Refresh%20Page) keyword currently has no optional parameters and it performs a "soft" refresh where POST data is kept. I would like to add functionality so that the page does a "force" refresh, which means it clears all the POST data and the gets new information from the website as it reloads.

**Describe the solution you'd like**
I would like a new optional parameter `force=true` (false by default) added to the [Refresh Page](https://qentinelqi.github.io/qweb/QWeb.html#Refresh%20Page) keyword so that it performs a refresh as described in the problem section above. 

**Describe alternatives you've considered**
Currently I am using the [Execute Javascript](https://qentinelqi.github.io/qweb/QWeb.html#Execute%20Javascript) keyword to perform the action with the browser itself.
```javascript
window.location.reload(true);   // the parameter value 'true' activates a forced refresh, may not work in all browsers
```

**Additional context**
- https://stackoverflow.com/questions/3715047/how-to-reload-a-page-using-javascript
- https://developer.mozilla.org/en-US/docs/Web/API/Location/reload

**Comment by tkoukkari** [comment]
Thanks for the proposal. Makes sense, I can see there being use cases where this is needed. We'll add it.

**Comment by tkoukkari** [comment]
Sorry, turns out this doesn't work too reliably with all major browsers. We ended up not adding it after all. I hope you understand.
