### ISSUE TITLE
Add community website to this repository settings

### ISSUE THREAD

**Issue by kalyncoose** [qentinelqi/qweb#49]
Hello! I've completed the community website, but will continue to add more QWeb examples and eventually a playground-type page. Please give me any feedback for the community website and add the URL to this repository's "About": https://www.qweblibrary.org

**Other Information**:
- Website Repo: https://github.com/kalyncoose/qweb-org
- Website Framework: [Vue.js 2.0](https://vuejs.org/)
- UI Components: [Vuetify](https://vuetifyjs.com)
- Domain ($9.99 for first year paid): qweblibrary.org
- Hosted: AWS Route53
- Deployed: AWS Amplify us-east-1
- Usability Testing: Firefox, Chrome on Windows 10 and Safari on iOS 14
- Comments: Website is fully responsive, only minor text-wrapping issues on some pages on mobile.

**Comment by tkoukkari** [comment]
Thank you for these nice, new pages. Added!
