### ISSUE TITLE
Log Screenshot - Add optional parameter to capture full window

### ISSUE THREAD

**Issue by kalyncoose** [qentinelqi/qweb#61]
**Is your feature request related to a problem? Please describe.**
The [Log Screenshot](https://qentinelqi.github.io/qweb/QWeb.html#Log%20Screenshot) keyword currently only takes a screenshot of the visible window, so elements beyond the current scroll position are cut off from the screenshot.

**Describe the solution you'd like**
The [Log Screenshot](https://qentinelqi.github.io/qweb/QWeb.html#Log%20Screenshot) keyword should have an optional parameter, perhaps called `full_page`, that accepts a boolean value. If `full_page=True`, then QWeb should take a full page screenshot so that nothing is cut off from view. `full_page` should be set to `False` by default.

**Describe alternatives you've considered**
The other popular library for screenshots, [ScreenCapLibrary](https://mihaiparvu.github.io/ScreenCapLibrary/ScreenCapLibrary.html#Take%20Screenshot), does not seem to support this idea of full page screenshot either.

**Additional context**
Could QWeb support this or is this request outside of QWeb's available functionality with the web driver?

**Comment by tkoukkari** [comment]
Thanks, good idea. We'll discuss about it. As far as I know this could already be done "natively" with Firefox, but for other browsers we would need different solution.
