### ISSUE TITLE
QWeb requires old Selenium

### ISSUE THREAD

**Issue by squrppi** [qentinelqi/qweb#68]
QWeb 1.2.5 requires Selenium 3.141.0, while robotframework-seleniumlibrary requires Selenium >=4.0.0. This causes issues if both are needed in the same installation.

QWeb should use Selenium>=4.0.0.

**Comment by tkoukkari** [comment]
hi, yes. We already have a release candidate (QWeb 2.0.0rc1) with selenium 4 which can be installed with:
`pip install -U QWeb --pre`

Selenium 4 will also be the only supported selenium version in next official release.

I'll leave this issue open until next release will be available in pypi without --pre flag.

**Comment by tkoukkari** [comment]
2.0.0 was released today with selenium 4 support.
