### ISSUE TITLE
VerifyElementText doesn't highlight the elementtext under test when running the test case

### ISSUE THREAD

**Issue by nico-lundqvist** [qentinelqi/qweb#74]
When running test with keyword VerifyElementText it doesn't highlight the element text under test. It would be improvement to see and confirm that the keyword tests certain element text with anchor (because the same text can be multiple times in different places on the page).  

Example:
`VerifyElementText    ipsum    ipsum    5    dolore`

`    SetConfig    SearchMode           Draw`
Doesn't work either with VerifyElementText

**Comment by tkoukkari** [comment]
Thank you for reporting this. We'll check and fix it. Should be part of next release (2.0.2)
